#!/usr/bin/env node
const log = require('./logger');

log.info('Drone downstream registry plugin');

try {
  log.info('Reading and verifying parameters');
  const params = require('./params');

  log.info('Building registry file storage');
  const storage = require('./fileStorage')(params.plugin.registryPath);

  log.info('Building registry');
  const registry = require('./registry')(storage);

  switch (params.plugin.action) {
    case 'package-build':
      log.info('Executing [package-build]');
      registry.createPackageEntry(
        params.registry.package,
        params.registry.version,
        params.plugin.repositories
      );
      break;

    case 'downstream-build':
      log.info('Executing [downstream-build]');
      registry.registerDownstreamBuild(
        params.registry.package,
        params.registry.version,
        params.registry.buildRepo,
        params.registry.buildStatus,
        params.registry.buildNumber
      );

      const status = registry.currentPackageStatus(
        params.registry.package,
        params.registry.version
      );

      log.info(`Current package cumulative status: ${status.toUpperCase()}`);

      break;
  }
} catch (e) {
  log.error(`Error: ${e.message}`);
  process.exit(1);
}


